---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: GRPCRoute
metadata:
  name: cache-route
spec:
  parentRefs:
    - name: cache-gateway
      sectionName: cache-gateway
  rules:
    - backendRefs:
        - name: nativelink-cas
          port: 50051
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: GRPCRoute
metadata:
  name: scheduler-route
spec:
  parentRefs:
    - name: scheduler-gateway
      sectionName: scheduler-gateway
  rules:
    - backendRefs:
        - name: nativelink-scheduler
          port: 50052
