---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -core

components:
  - ../../components/alerts
  - ../../components/kustomization

replacements:
  - source:
      kind: Kustomization
      name: nativelink
      fieldPath: metadata.name
    targets:
      - select:
          kind: Alert
          name: nativelink-alert
        fieldPaths:
          - spec.eventMetadata.configMapName
      - select:
          kind: Kustomization
          name: nativelink
        fieldPaths:
          - spec.postBuild.substituteFrom.0.name

patches:
- patch: |-
    - op: replace
      path: /spec/eventMetadata/flakeOutput
      value: github:TraceMachina/nativelink#image
  target:
    kind: Alert
    name: nativelink-alert
- patch: |-
    - op: replace
      path: /spec/path
      value: ./kubernetes/nativelink
    - op: add
      path: /spec/images
      value:
      - name: nativelink
        newName: localhost:5001/nativelink
        newTag: ${NATIVELINK_TAG}
  target:
    kind: Kustomization
    name: nativelink
