---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: tekton-route
  namespace: tekton-pipelines
spec:
  parentRefs:
    - name: tkn-gateway
      namespace: default
      sectionName: tkn-gateway
  rules:
    - matches:
        - path:
            value: /
      backendRefs:
        - name: tekton-dashboard
          port: 9097
