apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
- ../../kubernetes/components/operator

patches:
- patch: |-
    - op: replace
      path: /spec/path
      value: ./kubernetes/overlays/lre
  target:
    kind: Kustomization
    name: nativelink
- patch: |-
    - op: replace
      path: /spec/url
      value: https://github.com/aaronmondal/nativelink
  target:
    kind: GitRepository
    name: nativelink
- patch: |-
    - op: replace
      path: /spec/ref/branch
      value: flux
  target:
    kind: GitRepository
    name: nativelink
- patch: |-
    - op: replace
      path: /spec/eventMetadata/flakeOutput
      value: github:aaronmondal/nativelink/flux#nativelink-worker-lre-cc
  target:
    kind: Alert
    name: nativelink-worker-alert
- patch: |-
    - op: replace
      path: /spec/eventMetadata/flakeOutput
      value: github:aaronmondal/nativelink/flux#image
  target:
    kind: Alert
    name: nativelink-image-alert
- patch: |-
    - op: replace
      path: /spec/eventMetadata/flakeOutput
      value: github:aaronmondal/nativelink/flux#nativelink-worker-init
  target:
    kind: Alert
    name: nativelink-worker-init-alert
