---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

components:
- ../../components/gateway-routes
- ../../components/insecure-certs

patches:
- path: worker-lre-cc.yaml
  target:
    kind: Deployment
    name: nativelink-worker

images:
  - name: nativelink
    newName: localhost:5001/nativelink
    newTag: ${NATIVELINK_TAG}
  - name: nativelink-worker-init
    newName: localhost:5001/nativelink-worker-init
    newTag: ${NATIVELINK_WORKER_INIT_TAG}
  - name: nativelink-worker
    newName: localhost:5001/nativelink-worker-lre-cc
    newTag: ${NATIVELINK_WORKER_LRE_CC_TAG}
