# Copyright 2024 The NativeLink Authors. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is @generated by lre-rs.

"""Module extension to register different lre-rs tool repositories."""

load("@bazel_tools//tools/build_defs/repo:local.bzl", "new_local_repository")

# TODO(aaronmondal): Using module extensions here isn't optimal as it doesn't
#                    allow overriding tools via environment variables.
#                    Unfortunately rules_rust's rust_toolchain currently
#                    requires tools to be declared via labels to filegroups,
#                    so we need the new_local_repository approach here.
#                    Add support for raw strings to rules_rust upstream so
#                    that we can remove this module extension entirely.

def _lre_rs_impl(_mctx):
    new_local_repository(
        name = "lre-rs-stable-aarch64-darwin",
        build_file = "@local-remote-execution//rust:aarch64-darwin.BUILD.bazel",
        path = "/nix/store/vpn2yd6zxns3xavmg1dg8bqn0hvbdnz9-rust-default-1.85.0",
    )
    new_local_repository(
        name = "lre-rs-nightly-aarch64-darwin",
        build_file = "@local-remote-execution//rust:aarch64-darwin.BUILD.bazel",
        path = "/nix/store/sbvqaza6qwia3y4kp6r01va1qkbw6pvf-rust-default-1.87.0-nightly-2025-02-21",
    )
    new_local_repository(
        name = "lre-rs-stable-aarch64-linux",
        build_file = "@local-remote-execution//rust:aarch64-linux.BUILD.bazel",
        path = "/nix/store/wz5fc8crygf2fas3anjysbqn3xz838mz-rust-default-1.85.0",
    )
    new_local_repository(
        name = "lre-rs-nightly-aarch64-linux",
        build_file = "@local-remote-execution//rust:aarch64-linux.BUILD.bazel",
        path = "/nix/store/lg4vbvfdx7f89ams0q0i8x5mrd3345fd-rust-default-1.87.0-nightly-2025-02-21",
    )
    new_local_repository(
        name = "lre-rs-stable-x86_64-darwin",
        build_file = "@local-remote-execution//rust:x86_64-darwin.BUILD.bazel",
        path = "/nix/store/3603032a6xfww1hadhii9c9bz0xwqsxr-rust-default-1.85.0",
    )
    new_local_repository(
        name = "lre-rs-nightly-x86_64-darwin",
        build_file = "@local-remote-execution//rust:x86_64-darwin.BUILD.bazel",
        path = "/nix/store/ah5ycb17kjqh25iq9lblxps8z4lj9svc-rust-default-1.87.0-nightly-2025-02-21",
    )
    new_local_repository(
        name = "lre-rs-stable-x86_64-linux",
        build_file = "@local-remote-execution//rust:x86_64-linux.BUILD.bazel",
        path = "/nix/store/xb66ccsqp268mx2bx9j7dspp2if4ya0z-rust-default-1.85.0",
    )
    new_local_repository(
        name = "lre-rs-nightly-x86_64-linux",
        build_file = "@local-remote-execution//rust:x86_64-linux.BUILD.bazel",
        path = "/nix/store/fgsghgy7y8hgh2d4bajmgjlykpffzs4n-rust-default-1.87.0-nightly-2025-02-21",
    )

lre_rs = module_extension(implementation = _lre_rs_impl)
