---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 2m
  path: "./kubernetes/resources/cert-manager"
  prune: true
  force: true
  retryInterval: 20s
  # We don't set targetNamespace for this one as the cert-manager kustomization
  # needs to create the namespace itself.
  wait: true
  sourceRef:
    kind: GitRepository
    name: nativelink
    namespace: flux-system
