---
resources:
  - cas.yaml
  - scheduler.yaml
  - worker-lre-cc.yaml
  - worker-lre-java.yaml
  - routes.yaml

configMapGenerator:
  - name: cas
    files:
      - cas.json
  - name: scheduler
    files:
      - scheduler.json
  - name: worker-lre-cc
    files:
      - worker-lre-cc.json
  - name: worker-lre-java
    files:
      - worker-lre-java.json

secretGenerator:
  - name: tls-secret
    files:
      - example-do-not-use-in-prod-rootca.crt
      - example-do-not-use-in-prod-key.pem
