---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -siso-chromium

components:
  - ../../../components/kustomization


patches:
- patch: |-
    - op: replace
      path: /spec/path
      value: ./kubernetes/workers/siso-chromium
    - op: replace
      path: /spec/postBuild/substituteFrom/0
      value:
        kind: ConfigMap
        name: nativelink-worker-init
    - op: add
      path: /spec/images
      value:
      - name: nativelink-worker-init
        newName: localhost:5001/nativelink-worker-init
        newTag: ${NATIVELINK_WORKER_INIT_TAG}
      - name: nativelink-worker-siso-chromium
        newName: gcr.io/chops-public-images-prod/rbe/siso-chromium/linux
        # TODO(aaronmondal): This should be the sha256, but that's broken atm.
        newTag: ts-2025.01.07-1921
  target:
    kind: Kustomization
    name: nativelink
