[package]
name = "error"
version = "0.0.0"
edition = "2021"
autobins = false
autoexamples = false
autotests = false
autobenches = false

[dependencies]
proto = { path = "../proto" }

hex = "0.4.3"
prost = "0.11.9"
prost-types = "0.11.9"
tokio = { version = "1.35.0" }
tonic = { version = "0.9.2", features = ["gzip"] }
