---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: nativelink-image-alert
  namespace: flux-system
spec:
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: '*'
      namespace: default
  providerRef:
    name: nativelink-webhook
  eventMetadata:
    flakeOutput: github:TraceMachina/nativelink#image
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: nativelink-worker-init-alert
  namespace: flux-system
spec:
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: '*'
      namespace: default
  providerRef:
    name: nativelink-webhook
  eventMetadata:
    flakeOutput: github:TraceMachina/nativelink#nativelink-worker-init
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: nativelink-worker-alert
  namespace: flux-system
spec:
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: '*'
      namespace: default
  providerRef:
    name: nativelink-webhook
  eventMetadata:
    flakeOutput: "PLACEHOLDER_NATIVELINK_WORKER"
