---
name: Local Remote Execution

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: read-all

jobs:
  local:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
    name: Local / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:

      - name: Checkout
        uses: >- # v4.1.1
          actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Install Nix
        uses: >- # v9
          DeterminateSystems/nix-installer-action@cd46bde16ab981b0a7b2dce0574509104543276e
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          nix-installer-tag: v0.16.1

      - name: Cache Nix derivations
        uses: >- # Custom commit, last pinned at 2024-03-03.
          DeterminateSystems/magic-nix-cache-action@742d8701e54851d2136f71b61d31382a4f4d0788

      - name: Build hello_lre with LRE toolchain.
        run: >
          nix develop --impure --command
          bash -c "bazel run \
           --config=lre \
           --verbose_failures \
           @local-remote-execution//examples:hello_lre"

      - name: Build NativeLink with LRE.
        run: >
          nix develop --impure --command
          bash -c "bazel test \
           --config=lre \
           --verbose_failures \
           ..."


  remote:
    strategy:
      fail-fast: false
      matrix:
        os: [large-ubuntu-22.04]
    name: Remote / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: >- # v4.1.1
          actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Install Nix
        uses: >- # v9
          DeterminateSystems/nix-installer-action@cd46bde16ab981b0a7b2dce0574509104543276e
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          nix-installer-tag: v0.16.1

      - name: Cache Nix derivations
        uses: >- # Custom commit, last pinned at 2024-03-03.
          DeterminateSystems/magic-nix-cache-action@742d8701e54851d2136f71b61d31382a4f4d0788

      - name: Start Kubernetes cluster (Infra)
        run: >
          nix run .#native up

      - name: Start Kubernetes cluster (Operations)
        run: >
          nix develop --impure --command
          bash -c "./deployment-examples/kubernetes/01_operations.sh"

      - name: Start Kubernetes cluster (Application)
        run: >
          nix develop --impure --command
          bash -c "./deployment-examples/kubernetes/02_application.sh"

      - name: Get gateway IPs
        id: gateway-ips
        run: |
          echo "cache_ip=$(kubectl get gtw cache -o=jsonpath='{.status.addresses[0].value}')" >> "$GITHUB_ENV"
          echo "scheduler_ip=$(kubectl get gtw scheduler -o=jsonpath='{.status.addresses[0].value}')" >> "$GITHUB_ENV"

      - name: Print cluster state
        run: |
          kubectl get svc -A
          kubectl get pod -A
          kubectl get svc -A
          kubectl get deployments -A
          kubectl describe gtw
          echo "cas"
          kubectl logs -l app=nativelink-cas
          echo "scheduler"
          kubectl logs -l app=nativelink-scheduler
          echo "worker"
          kubectl logs -l app=nativelink-worker

      - name: Build hello_lre with LRE toolchain.
        run: >
          nix develop --impure --command
          bash -c "bazel run \
            --config=lre \
            --remote_instance_name=main \
            --remote_cache=grpc://$cache_ip:50051 \
            --remote_executor=grpc://$scheduler_ip:50052 \
            --verbose_failures \
            @local-remote-execution//examples:hello_lre"

      - name: Build NativeLink with LRE.
        run: >
          nix develop --impure --command
          bash -c "bazel test \
            --config=lre \
            --remote_instance_name=main \
            --remote_cache=grpc://$cache_ip:50051 \
            --remote_executor=grpc://$scheduler_ip:50052 \
            --verbose_failures \
            ..."
