---
name: Nix

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: read-all

jobs:
  nix-bazel:
    runs-on: ubuntu-22.04
    steps:

      - name: Checkout
        uses: >- # v4.1.1
          actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Install Nix
        uses: >- #v7
          DeterminateSystems/nix-installer-action@5620eb4af6b562c53e4d4628c0b6e4f9d9ae8612

      - name: Cache Nix derivations
        uses: >- # Custom commit, last pinned at 2023-11-17.
          DeterminateSystems/magic-nix-cache-action@a04e6275a6bea232cd04fc6f3cbf20d4cb02a3e1

      - name: Mount bazel cache
        uses: > # v3.3.2
          actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84
        with:
          path: "~/.cache/bazel"
          key: ${{ runner.os }}-bazel-nix

      - name: Invoke Bazel build in Nix shell
        run: >
          nix develop --impure --command
          bash -c "bazel test ..."

  nix-cargo:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: >- # v4.1.1
          actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Install Nix
        uses: >- #v7
          DeterminateSystems/nix-installer-action@5620eb4af6b562c53e4d4628c0b6e4f9d9ae8612

      - name: Cache Nix derivations
        uses: >- # Custom commit, last pinned at 2023-11-17.
          DeterminateSystems/magic-nix-cache-action@a04e6275a6bea232cd04fc6f3cbf20d4cb02a3e1

      - name: Invoke Cargo build in Nix shell
        run: >
          nix develop --impure --command
          bash -c "cargo test --all"
